### ISSUE TITLE
Is there any way to get intellisense and goto functionality on autoimported components?

### ISSUE THREAD

**Issue by EngHell** [antfu/vite-plugin-components#36]
So far a great plugin, but it loses the most important part of typescript, typechecking and not only that goto does not work neither in volar or vetur.

**Comment by onx2** [comment]
This would be an awesome feature 😄 

I have a workaround that is okay for my use case but probably not for all. I want to build out a component library and I'd like to import all components to test in the `App.vue` file. This isn't a good workaround for a real world app though. Here's what I'm doing instead of using this plugin (until I get type defs):

```vue
<script lang="ts">
import { defineComponent } from "vue"
import * as Components from "./lib"

export default defineComponent({
  name: "App",
  components: { ...Components },
  setup() {
    return { }
  },
})
</script>
```

**Comment by EngHell** [comment]
Yep, currently i cant use this workarround, Since im building an app that will be published and not just test the components, if im not mistaken probably a plugin for typescript should be written and it should share the same resolver logic as this vite plugin.

I don't have the knowledge on typescript plugins nor the time in my hands for some months to look at this or would do.

**Comment by antfu** [comment]
Awaiting this https://github.com/vuejs/vue-next/pull/3399

**Comment by EngHell** [comment]
this is great news, even better than what i expected

**Comment by antfu** [comment]
Supported in v0.10.2 with Volar
