### ISSUE TITLE
[Question] How lazy loaded components is supported?

### ISSUE THREAD

**Issue by paulorodrigues-mb** [antfu/vite-plugin-components#46]
Hello guys, new here.

The readme says that code splitting is supported, but how?
 
Any example?

Thank you!

**Comment by 7architect** [comment]
lazy loading seems not supported https://github.com/antfu/vite-plugin-components/blob/3a38b5358d0ed3f025fd0b8c9e5f2723b24c349b/src/utils.ts#L72

**Comment by Heartnett** [comment]
+1

**Comment by Heartnett** [comment]
> lazy loading seems not supported
> 
> https://github.com/antfu/vite-plugin-components/blob/3a38b5358d0ed3f025fd0b8c9e5f2723b24c349b/src/utils.ts#L72

False advertising :stuck_out_tongue_winking_eye:

**Comment by antfu** [comment]
This plugin does not support lazy components and have no plan to (you'd better explicitly import them asynchronously).

"code splitting" is based on the fact you make your components entries asynchronous (for example, page routes), the auto imported components will be split into that async chunks if they're the only usage (instead of some solutions that register all your components globally).

**Comment by kissu** [comment]
```js
const asyncButton = defineAsyncComponent(() => import('~/components/Button.vue'))
```
is working great, indeed!

If I understand properly, the lazy import is not doable because we register those components globally?
Something like [Nuxt lazy components](https://nuxtjs.org/tutorials/improve-your-developer-experience-with-nuxt-components/#lazy-loading-your-components) is not done in the same way? It is not possible here?
